routes/web.php
<?php

use App\Http\Controllers\DiagnosticoController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\VersionController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    // Listado de pacientes
    Route::get('/', [PacienteController::class, 'index'])->name('pacientes.index');

    // CRUD de pacientes
    Route::resource('pacientes', PacienteController::class);

    Route::group([
        'prefix' => 'pacientes/{paciente}',
        'as' => 'pacientes.',
    ], function () {
        // Diagnosticos de paciente
        Route::resource('diagnosticos', DiagnosticoController::class)->only('store', 'create');

        // Versiones de datos de paciente
        Route::get('versiones', [VersionController::class, 'versionesPaciente'])->name('versiones');
    });

    // Diagnosticos (show, edit, update, destroy)
    Route::resource('diagnosticos', DiagnosticoController::class)->except('create', 'store', 'index');

    Route::group([
        'prefix' => 'diagnosticos/{diagnostico}',
        'as' => 'diagnosticos.',
    ], function () {
        // Versiones de datos de diagnosticos
        Route::get('versiones', [VersionController::class, 'versionesDiagnostico'])->name('versiones');
    });
});

app/Models/Version.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Version extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = [
        'fecha',
        'model_type',
        'model_id',
        'data',
    ];
}

app/Http/Controllers/VersionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Diagnostico;
use App\Models\Paciente;
use App\Models\Version;
use Illuminate\Http\Request;

class VersionController extends Controller
{
    /**
     * Mostramos el listado con las versiones de datos del paciente
     *
     * @param \App\Models\Paciente
     * @return \Illuminate\Http\Response
     */
    public function versionesPaciente(Paciente $paciente)
    {
        return view('version.paciente', compact('paciente'));
    }

    /**
     * Mostramos el listado con las versiones de datos del diagnóstico
     *
     * @param \App\Models\Diagnostico
     * @return \Illuminate\Http\Response
     */
    public function versionesDiagnostico(Diagnostico $diagnostico)
    {
        return view('version.diagnostico', compact('diagnostico'));
    }
}

resources/views/version/diagnostico.blade.php
@extends('layouts.app')

@section('title', 'Versiones de datos de diagnóstico')

@section('content')
    {!! Form::model($diagnostico) !!}
    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Datos actuales del diagnóstico
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4 form-group">
                            <label>Fecha</label>
                            {!! Form::text('fecha', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-12 form-group">
                            <label>Descripción</label>
                            {!! Form::textarea('descripcion', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-12">
                            <p class="text-right">
                                <a class="btn btn-warning" href="{{ route('pacientes.show', $diagnostico->paciente_id) }}">
                                    <i class="fas fa-arrow-left pr-2"></i>Volver a la ficha del paciente
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Versiones de datos
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if($diagnostico->versiones->isEmpty())
                                <p class="alert alert-warning text-center">No existen versiones de datos del diagnóstico</p>
                            @else
                                <div class="table-responsive">
                                    <table class="table table-hover table-striped">
                                        <colgroup>
                                            <col width="50">
                                            <col width="100">
                                            <col width="100">
                                            <col>
                                        </colgroup>
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Fecha V.</th>
                                                <th>Fecha D.</th>
                                                <th>Descripción</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach ($diagnostico->versiones as $version)
                                                @php
                                                    $data_version = json_decode($version->data);
                                                @endphp

                                                <tr data-id="{{ $version->id }}">
                                                    <td>{{ $version->id }}</td>
                                                    <td>{{ date('d/m/Y H:i', strtotime($version->fecha)) }}</td>
                                                    <td>{{ date('d/m/Y', strtotime($data_version->fecha)) }}</td>
                                                    <td>{{ Crypt::decryptString($data_version->descripcion) }}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/version/paciente.blade.php
@extends('layouts.app')

@section('title', 'Versiones de datos de paciente')

@section('content')
    {!! Form::model($paciente) !!}
    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Datos actuales del paciente
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9 form-group">
                            <label>Nombre completo</label>
                            {!! Form::text('nombre_apellidos', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-3 form-group">
                            <label>DNI</label>
                            {!! Form::text('dni', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-12">
                            <p class="text-right">
                                <a class="btn btn-warning" href="{{ route('pacientes.show', $paciente->id) }}">
                                    <i class="fas fa-arrow-left pr-2"></i>Volver a la ficha del paciente
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Versiones de datos
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if($paciente->versiones->isEmpty())
                                <p class="alert alert-warning text-center">No existen versiones de datos del paciente</p>
                            @else
                                <div class="table-responsive">
                                    <table class="table table-hover table-striped">
                                        <colgroup>
                                            <col width="50">
                                            <col width="100">
                                            <col>
                                            <col width="105">
                                        </colgroup>
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Fecha V.</th>
                                                <th>Nombre completo</th>
                                                <th>DNI</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach ($paciente->versiones as $version)
                                                @php
                                                    $data_version = json_decode($version->data);
                                                @endphp

                                                <tr data-id="{{ $version->id }}">
                                                    <td>{{ $version->id }}</td>
                                                    <td>{{ date('d/m/Y H:i', strtotime($version->fecha)) }}</td>
                                                    <td>{{ Crypt::decryptString($data_version->nombre_apellidos) }}</td>
                                                    <td>{{ Crypt::decryptString($data_version->dni) }}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection