routes/web.php
<?php

use App\Http\Controllers\DiagnosticoController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\VersionController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    // Listado de pacientes
    Route::get('/', [PacienteController::class, 'index'])->name('pacientes.index');

    // CRUD de pacientes
    Route::resource('pacientes', PacienteController::class);

    Route::group([
        'prefix' => 'pacientes/{paciente}',
        'as' => 'pacientes.',
    ], function () {
        // Diagnosticos de paciente
        Route::resource('diagnosticos', DiagnosticoController::class)->only('store', 'create');

        // Versiones de datos de paciente
        Route::get('versiones', [VersionController::class, 'versionesPaciente'])->name('versiones');
    });

    // Diagnosticos (show, edit, update, destroy)
    Route::resource('diagnosticos', DiagnosticoController::class)->except('create', 'store', 'index');

    Route::group([
        'prefix' => 'diagnosticos/{diagnostico}',
        'as' => 'diagnosticos.',
    ], function () {
        // Versiones de datos de diagnosticos
        Route::get('versiones', [VersionController::class, 'versionesDiagnostico'])->name('versiones');
    });
});

resources/views/partials/js.blade.php
<script>
    var browserSyncActive = false;

    $(function () {
        $('.btn-back').click(function (e) {
            var url = '{{ url()->previous() }}';
            if (! url.length || url == window.location.href || ! url.includes('{{ url('/') }}')) {
                url = '{{ url('/') }}\/' + $('meta[name="uri"]').attr('content');
            }

            window.location.href = url;
        });
    });
</script>

resources/views/partials/navbar.blade.php
<!-- top navbar-->
<header class="topnavbar-wrapper">
    <!-- START Top Navbar-->
    <nav class="navbar navbar-light topnavbar">
        <!-- START Left navbar-->
        <ul class="navbar-nav mr-auto flex-row">
            <li class="nav-item">
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed">
                    <em class="fas fa-bars"></em>
                </a>
                <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true">
                    <em class="fas fa-bars"></em>
                </a>
            </li>
        </ul>
        <!-- END Left navbar-->
        <!-- START Right Navbar-->
        <ul class="navbar-nav flex-row">
            <!-- START Offsidebar button-->
            <li class="nav-item">
                <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" data-toggle-state="offsidebar-open" data-no-persist="true">
                    <em class="icon-logout pr-2"></em>
                    {{ __('Cerrar sesión') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
            <!-- END Offsidebar menu-->
        </ul>
    </nav>
<!-- END Top Navbar-->
</header>

resources/views/partials/notify.blade.php
@if ($errors->any())
    <div class="row">
        <div class="col-12">
            <div class="alert alert-danger fade show" role="alert">
                <div class="row">
                    <div class="col-auto pr-0">
                        <span class="fas fa-exclamation-circle fa-lg mr-2" aria-hidden="true"></span>
                    </div>
                    <div class="col pl-0">
                        <strong>Se han detectado los siguientes errores: </strong><br>
                        @foreach ($errors->all() as $error)
                            {{ $error }}<br />
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/partials/sidebar.blade.php
@php $path = Request::path() @endphp

<!-- sidebar-->
<aside class="aside-container">
    <!-- START Sidebar (left)-->
    <div class="aside-inner">
        <nav class="sidebar" data-sidebar-anyclick-close="">
            <!-- START sidebar nav-->
            <ul class="sidebar-nav">
                <li class="has-user-block">
                    <div id="user-block">
                        <div class="item user-block">
                            <!-- Name and Job-->
                            <div class="user-block-info">
                                <span class="user-block-name">Hola, {{ Auth::user()->name }}</span>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="{{ request()->is('/') || request()->is('pacientes*') ? 'active' : '' }}">
                    <a href="{{ route('pacientes.index') }}" title="Pacientes">
                        <em class="fas fa-users fa-fw"></em>
                        <span>Pacientes</span>
                    </a>
                </li>

                {{-- <li class="{{ request()->is('diagnosticos*') ? 'active' : '' }}">
                    <a href="{{ route('diagnosticos.index') }}" title="Usuarios">
                        <em class="fas fa-users fa-fw"></em>
                        <span>Diagnosticos</span>
                    </a>
                </li> --}}
            </ul>
            <!-- END sidebar nav-->
        </nav>
    </div>
    <!-- END Sidebar (left)-->
</aside>