routes/web.php
<?php

use App\Http\Controllers\DiagnosticoController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\VersionController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::middleware('auth')->group(function () {
    // Listado de pacientes
    Route::get('/', [PacienteController::class, 'index'])->name('pacientes.index');

    // CRUD de pacientes
    Route::resource('pacientes', PacienteController::class);

    Route::group([
        'prefix' => 'pacientes/{paciente}',
        'as' => 'pacientes.',
    ], function () {
        // Diagnosticos de paciente
        Route::resource('diagnosticos', DiagnosticoController::class)->only('store', 'create');

        // Versiones de datos de paciente
        Route::get('versiones', [VersionController::class, 'versionesPaciente'])->name('versiones');
    });

    // Diagnosticos (show, edit, update, destroy)
    Route::resource('diagnosticos', DiagnosticoController::class)->except('create', 'store', 'index');

    Route::group([
        'prefix' => 'diagnosticos/{diagnostico}',
        'as' => 'diagnosticos.',
    ], function () {
        // Versiones de datos de diagnosticos
        Route::get('versiones', [VersionController::class, 'versionesDiagnostico'])->name('versiones');
    });
});

app/Models/Paciente.php
<?php

namespace App\Models;

use App\Models\Paciente as ModelsPaciente;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;

class Paciente extends Model
{
    use HasFactory;
    use SoftDeletes;
    use Userstamps;

    protected $fillable = [
        'nombre_apellidos',
        'dni',
    ];

    /**
     * Encriptamos las cadenas sensibles
     *
     * @var array
     */
    protected $casts = [
        'nombre_apellidos' => 'encrypted',
        'dni' => 'encrypted',
    ];

    /**
     * Obtener todos los diagnósticos de un paciente
     */
    public function diagnosticos()
    {
        return $this->hasMany(Diagnostico::class);
    }

    /**
     * Obtener todas las versiones de datos de un paciente
     */
    public function versiones()
    {
        return $this->morphMany(Version::class, 'versiones', 'model_type', 'model_id');
    }

    /**
     * Scope a query to filter.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  array  $data
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFilter(Builder $query, array $data)
    {
        if (!empty($search = $data['search'] ?? null)) {
            $query->where(function ($query) use ($search) {
                $query->where('nombre_apellidos', 'like', "%{$search}%")
                    ->orWhere('dni', 'like', "%{$search}%");
            });
        } elseif (!empty($search = $data['id'] ?? null)) {
            $query->where('id', $search);
        }

        return $query;
    }
}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PacienteSearchRequest;
use App\Http\Requests\PacientesStoreRequest;
use App\Http\Requests\PacienteUpdateRequest;
use App\Models\Diagnostico;
use App\Models\Paciente;
use App\Models\Version;
use Illuminate\Http\Request;

class PacienteController extends Controller
{
    /**
     * Mostrar el listado filtrable de pacientes
     *
     * @param  \App\Http\Requests\PacienteSearchRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function index(PacienteSearchRequest $request)
    {
        $pacientes = Paciente::all();

        return view('paciente.index', compact('pacientes'));
    }

    /**
     * Mostrar el formulario de creación de paciente
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('paciente.create');
    }

    /**
     * Guardar la información insertada del paciente
     *
     * @param  \App\Http\Requests\PacientesStoreRequest;  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PacientesStoreRequest $request)
    {
        $data = $request->validated();
        Paciente::create($data);

        session()->flash('alert-success', 'El paciente se ha creado correctamente.');
        return redirect()->route('pacientes.index');
    }

    /**
     * Mostrar la info de un paciente junto con los diagnósticos del mismo
     *
     * @param  \App\Models\Paciente  $paciente
     * @return \Illuminate\Http\Response
     */
    public function show(Paciente $paciente)
    {
        // cargamos los diagnosticos del paciente ordenados por fecha descendente (más recientes primero)
        $diagnosticos = $paciente->diagnosticos()->orderBy('fecha', 'desc')->get();

        if ($paciente) {
            return view('paciente.show', compact('paciente', 'diagnosticos'));
        } else {
            session()->flash('alert-error', 'El paciente seleccionado no existe.');
            return redirect()->route('pacientes.index');
        }
    }

    /**
     * Mostrar el formulario de edición de los datos del paciente
     *
     * @param  \App\Models\Paciente  $paciente
     * @return \Illuminate\Http\Response
     */
    public function edit(Paciente $paciente)
    {
        return view('paciente.edit', compact('paciente'));
    }

    /**
     * Actualizar la información de los datos del paciente
     *
     * @param  \App\Http\Requests\PacienteUpdateRequest  $request
     * @param  \App\Models\Paciente  $paciente
     * @return \Illuminate\Http\Response
     */
    public function update(PacienteUpdateRequest $request, Paciente $paciente)
    {
        $data = $request->validated();
        // almacenamos la info anterior como version
        $data_version['fecha'] = date('Y-m-d H:i:s');
        $data_version['model_type'] = Paciente::class;
        $data_version['model_id'] = $paciente->id;
        $data_version['data'] = json_encode($paciente->getAttributes());

        Version::create($data_version);

        // almacenamos la info nueva
        $paciente->fill($data);
        $paciente->save();

        session()->flash('alert-success', 'Se ha editado el paciente correctamente.');
        return redirect()->route('pacientes.show', $paciente->id);
    }

    /**
     * Borrar de forma lógica (con softdelete) el paciente seleccionado
     *
     * @param  \App\Models\Paciente  $paciente
     * @return \Illuminate\Http\Response
     */
    public function destroy(Paciente $paciente)
    {
        // Al tener en la estructura de la tabla diagnostico "CascadeOnDelete"
        // no es necesario borrar los diagnosticos del paciente ya que lo hace de forma interna

        if ($paciente->delete()) {
            return response()->json(['message' => 'ok'], 202);
        }

        return response()->json(['error' => 'Internal Server Error'], 500);
    }
}

resources/views/paciente/create.blade.php
@extends('layouts.app')

@section('title', 'Nuevo paciente')

@section('content')

    {!! Form::open(['route' => 'pacientes.store', 'method' => 'POST']) !!}
        @include('paciente.fields')

        <div class="row">
            <div class="col-xl-8 col-xxl-6 text-right">
                <button class="btn btn-primary" type="submit"><i class="fas fa-save pr-2"></i> Guardar</button>
            </div>
        </div>
    {!! Form::close() !!}

@endsection

resources/views/paciente/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar paciente')

@section('content')

    {!! Form::model($paciente, ['route' => ['pacientes.update', $paciente->id], 'method' => 'PUT']) !!}
        @include('paciente.fields')

        <div class="row">
            <div class="col-xl-8 col-xxl-6 text-right">
                <button class="btn btn-secondary btn-back mr-2" type="button"><i class="fas fa-times pr-2"></i> Cancelar</button>
                <button class="btn btn-primary" type="submit"><i class="fas fa-save pr-2"></i> Editar paciente</button>
            </div>
        </div>
    {!! Form::close() !!}

@endsection

resources/views/paciente/fields.blade.php
<div class="row">
    <div class="col-xl-8 col-xxl-6">
        <div class="card card-default">
            <div class="card-header">
                Datos personales
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9 form-group">
                        <label>Nombre completo<small class="text-danger">(*)</small></label>
                        {!! Form::text('nombre_apellidos', null, ['class' => 'form-control', 'required']) !!}
                    </div>
                    <div class="col-md-3 form-group">
                        <label>DNI <small class="text-danger">(*)</small></label>
                        {!! Form::text('dni', null, ['class' => 'form-control', 'required']) !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/paciente/index.blade.php
@extends('layouts.app')

@section('title', 'Gestión de pacientes')

@section('buttons')

    <ul class="list-inline list-unstyled mb-0">
        <li class="list-inline-item">
            <a class="btn btn-primary" href="{{ route('pacientes.create') }}">
                <i class="fas fa-plus pr-2"></i>Nuevo paciente
            </a>
        </li>
    </ul>

@endsection

@section('content')

    <div class="card card-default">
        <div class="card-body">
            <div id="filter" class="main-content">
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped">
                                <colgroup>
                                    <col width="50">
                                    <col>
                                    <col width="150">
                                    <col width="150">
                                </colgroup>
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nombre completo</th>
                                        <th>DNI</th>
                                        <th class="text-center">Opciones</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach ($pacientes as $paciente)
                                        <tr data-id="{{ $paciente->id }}">
                                            <td><a href="{{ route('pacientes.show', $paciente->id) }}">{{ $paciente->id }}</a></td>
                                            <td><a href="{{ route('pacientes.show', $paciente->id) }}">{{ $paciente->nombre_apellidos }}</a></td>
                                            <td><a href="{{ route('pacientes.show', $paciente->id) }}">{{ $paciente->dni }}</a></td>
                                            <td>
                                                <a href="{{ route('pacientes.show', $paciente->id) }}" title="Ver ficha de paciente"><i class="mr-2 fas fa-lg fa-eye"></i></a>
                                                <a href="{{ route('pacientes.versiones', $paciente->id) }}" title="Consultar histórico de versiones"><i class="mr-2 fas fa-lg fa-history"></i></a>
                                                <a href="{{ route('pacientes.edit', $paciente->id) }}" title="Editar paciente"><i class="mr-2 fas fa-lg fa-pencil-alt"></i></a>
                                                <a onclick="destroy({uri: 'pacientes', id: {{ $paciente->id }} });return false;" href="#" title="Borrar paciente"><i class="fas fa-trash fa-lg"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/paciente/show.blade.php
@extends('layouts.app')

@section('title', 'Ficha de paciente')

@section('content')
    {!! Form::model($paciente) !!}
    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Datos personales
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9 form-group">
                            <label>Nombre completo</label>
                            {!! Form::text('nombre_apellidos', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-3 form-group">
                            <label>DNI</label>
                            {!! Form::text('dni', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                        <div class="col-md-12">
                            <p class="text-right">
                                <a class="btn btn-warning mr-2" href="{{ route('pacientes.versiones', $paciente->id) }}">
                                    <i class="fas fa-history pr-2 "></i>Versiones de datos
                                </a>
                                <a class="btn btn-primary" href="{{ route('pacientes.edit', $paciente->id) }}">
                                    <i class="fas fa-pencil-alt pr-2"></i>Editar paciente
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

    <div class="row">
        <div class="col-xl-8 col-xxl-6">
            <div class="card card-default">
                <div class="card-header">
                    Diagnósticos del paciente
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if($paciente->diagnosticos->isEmpty())
                                <p class="alert alert-warning text-center">No existen diagnósticos del paciente</p>
                            @else
                                <div class="table-responsive">
                                    <p class="text-right">
                                        <a class="btn btn-primary" href="{{ route('pacientes.diagnosticos.create', $paciente) }}">
                                            <i class="fas fa-plus pr-2"></i>Añadir diagnostico
                                        </a>
                                    </p>

                                    <table class="table table-hover table-striped">
                                        <colgroup>
                                            <col width="50">
                                            <col>
                                            <col width="100">
                                            <col width="105">
                                        </colgroup>
                                        <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Descripción</th>
                                                <th>Fecha</th>
                                                <th class="text-center">Opciones</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach ($diagnosticos as $diagnostico)
                                                <tr data-id="{{ $diagnostico->id }}">
                                                    <td>{{ $diagnostico->id }}</td>
                                                    <td>{{ $diagnostico->descripcion }}</td>
                                                    <td>{{ date('d/m/Y', strtotime($diagnostico->fecha)) }}</td>
                                                    <td>
                                                        <a title="Consultar histórico de versiones" href="{{ route('diagnosticos.versiones', $diagnostico->id) }}"><i class="mr-2 fas fa-lg fa-history"></i></a>
                                                        <a title="Editar diagnóstico" href="{{ route('diagnosticos.edit', $diagnostico->id) }}"><i class="mr-2 fas fa-lg fa-pencil-alt"></i></a>
                                                        <a onclick="destroy({uri: 'diagnosticos', id: {{ $diagnostico->id }} });return false;" href="#" title="Borrar diagnóstico"><i class="fas fa-trash fa-lg"></i></a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection